"""Service-owned front matter for plain Markdown memory notes."""

import json
import os
import re
from datetime import datetime, timezone

import yaml

def _is_claims_path(path: str) -> bool:
    """Claims are never edited through memory; compare without case and with either slash (Windows/macOS ignore case)."""
    p = str(path).replace("\\", "/").casefold().lstrip("./")
    return p == "claims" or p.startswith("claims/")


def split_front_matter(text: str) -> tuple[dict | None, str, str | None]:
    """Parse a closed YAML front matter block without changing its body text."""
    if not text.startswith("---") or not text.splitlines() or text.splitlines()[0].strip() != "---":
        return None, text, None
    lines = text.splitlines(keepends=True)
    closing = next((index for index, line in enumerate(lines[1:], 1) if line.strip() == "---"), None)
    if closing is None:
        return None, text, "The opening front matter marker has no closing --- line."
    raw = "".join(lines[1:closing])
    body = "".join(lines[closing + 1:])
    try:
        metadata = yaml.safe_load(raw)
        if metadata is None:
            metadata = {}
        if not isinstance(metadata, dict):
            return None, text, "front matter must contain key and value fields"
    except yaml.YAMLError as exc:
        return None, text, str(exc)
    return metadata, body, None



def parse(text: str, path: str = "") -> tuple[dict, str]:
    """Return parsed metadata and the note body, excluding front matter."""
    raw, body, _ = split_front_matter(text)
    raw = raw or {}
    raw = {key: value.isoformat() if hasattr(value, "isoformat") else value
           for key, value in raw.items()}
    title = str(raw.get("title") or "").strip('"')
    if not title:
        heading = re.search(r"(?m)^#\s+(.+?)\s*#*\s*$", body)
        title = heading.group(1).strip() if heading else os.path.splitext(os.path.basename(path))[0]
    raw_tags = raw.get("tags", [])
    tags = ([str(tag) for tag in raw_tags] if isinstance(raw_tags, list)
            else re.findall(r"[\w-]+", str(raw_tags).strip("[]")))
    if not tags:
        tags = re.findall(r"(?<![\w])#([\w-]+)", body)
    return ({"title": title, "author": raw.get("author") or "owner",
             "run_id": raw.get("run_id") or "", "created": raw.get("created") or "",
             "updated": raw.get("updated") or "", "tags": sorted(set(tags))}, body)


def render(path: str, body: str, author: str, run_id: str = "", existing: str | None = None) -> tuple[dict, str]:
    """Replace caller front matter with metadata generated by the service."""
    path = os.path.normpath(path).replace(os.sep, "/").removeprefix("./")
    if _is_claims_path(path):
        return parse(body, path)[0], body
    if run_id and not re.fullmatch(r"[A-Za-z0-9-]{1,64}", run_id):
        raise ValueError("Run id must contain only letters, numbers, and hyphens (up to 64 characters)")
    old, _ = parse(existing, path) if existing else ({}, "")
    incoming_match = re.match(r"\A---\s*\n(.*?)\n---\s*\n?", body, re.S)
    custom_fields = []
    if incoming_match:
        custom_fields = [line for line in incoming_match.group(1).splitlines()
                         if not re.match(r"\s*(?:title|author|run_id|created|updated|tags):", line)]
    _, content = parse(body, path)
    heading = re.search(r"(?m)^#\s+(.+?)\s*#*\s*$", content)
    title = heading.group(1).strip() if heading else os.path.splitext(os.path.basename(path))[0]
    tags = set(re.findall(r"(?<![\w])#([\w-]+)", content))
    tags.update(tag for line in content.splitlines() if line.strip().startswith("tags:")
                for tag in re.findall(r"[\w-]+", line.partition(":")[2]))
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    meta = {"title": title, "author": author, "run_id": run_id,
            "created": old.get("created") or now, "updated": now, "tags": sorted(tags)}
    front = "---\n" + "\n".join((
        f"title: {json.dumps(meta['title'], ensure_ascii=False)}", f"author: {author}",
        f"run_id: {run_id}", f"created: {meta['created']}", f"updated: {now}",
        f"tags: [{', '.join(meta['tags'])}]", *custom_fields)) + "\n---\n"
    return meta, front + content.lstrip("\n")


def legacy_read(text: str) -> str:
    """Hide service metadata from older vault consumers while retaining custom front matter."""
    match = re.match(r"\A---\s*\n(.*?)\n---\s*\n?", text, re.S)
    if not match:
        return text
    custom = [line for line in match.group(1).splitlines()
              if not re.match(r"\s*(?:title|author|run_id|created|updated|tags):", line)]
    body = text[match.end():]
    if custom:
        service_run = re.search(r"(?m)^run_id:\s*(.*)$", match.group(1))
        if service_run:
            custom.append("run_id: " + service_run.group(1))
    return "---\n" + "\n".join(custom) + "\n---\n" + body if custom else body
