// Shell test: exactly five top-level options, each screen renders on-theme, keyboard shortcuts work.
// Run after `npx vite build` (check:ui does this). Uses the same mock backend as core.spec.mjs.
import { spawn } from 'node:child_process'
import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { chromium } from 'playwright'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const MOCK_PORT = 8788, UI_PORT = 4318, UI = `http://localhost:${UI_PORT}`
const procs = []
const start = (cmd, args, env = {}) => { const p = spawn(cmd, args, { cwd: root, env: { ...process.env, ...env }, stdio: 'ignore', detached: true }); procs.push(p); return p }
const cleanup = () => { for (const p of procs.reverse()) { try { process.kill(-p.pid, 'SIGTERM') } catch { /* gone */ } } procs.length = 0 }
process.on('exit', cleanup)
const waitHttp = async url => { for (let i = 0; i < 100; i++) { try { if ((await fetch(url)).status < 500) return } catch { /* not up */ } await new Promise(r => setTimeout(r, 200)) } throw new Error(`timeout ${url}`) }
let failures = 0
const check = (c, label) => { console.log(`[shell] ${c ? 'ok  ' : 'FAIL'} ${label}`); if (!c) failures++ }

let browser
try {
  start('node', ['mock/mock_server.mjs', String(MOCK_PORT)])
  await waitHttp(`http://localhost:${MOCK_PORT}/api/environments`)
  start('npx', ['vite', 'preview', '--port', String(UI_PORT), '--strictPort'], { GLACIER_API: `http://localhost:${MOCK_PORT}` })
  await waitHttp(UI)
  const exe = process.env.CHROMIUM_PATH || (existsSync('/opt/pw-browsers/chromium') ? '/opt/pw-browsers/chromium' : undefined)
  browser = await chromium.launch(exe ? { executablePath: exe } : {})
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } })
  const errors = []
  page.on('pageerror', e => errors.push(String(e)))
  await page.goto(UI, { waitUntil: 'networkidle' })
  await page.getByTestId('splash').waitFor()
  check(true, 'start screen shows on launch')
  await page.keyboard.press('Enter')
  await page.getByTestId('screen-home').waitFor()
  check(await page.getByTestId('splash').count() === 0, 'Enter on the start screen continues to Home')
  await page.getByTestId('starter').waitFor()
  check(/standard mode/.test(await page.getByTestId('starter-reason').textContent()), 'Home: Get started explains the suggested setup in plain words')
  await page.getByTestId('starter-pick-1').click()
  await page.getByTestId('starter-apply').click()
  await page.getByTestId('starter-done').waitFor()
  check(/Added 1 automation/.test(await page.getByTestId('starter-done').textContent()), 'Get started sets up only the picked automations')
  await page.getByTestId('starter-hide').click()
  check(await page.getByTestId('starter').count() === 0, 'Get started can be closed')

  const tabIds = await page.locator('[role=tablist] [role=tab]').evaluateAll(els => els.map(el => el.getAttribute('data-testid')))
  const tabs = await Promise.all(['home', 'ask', 'automations', 'memory', 'settings'].map(id => page.getByTestId(`nav-${id}`).textContent()))
  check(tabIds.join(',') === 'nav-home,nav-ask,nav-automations,nav-memory,nav-settings' && tabs.map(x => x.trim()).join(',') === 'Home,Ask,Automations,Memory,Settings', `exactly five English tabs (got ${tabs.join(',')})`)
  for (const t of ['home', 'ask', 'automations', 'memory', 'settings']) {
    await page.getByTestId(`nav-${t}`).click()
    await page.getByTestId(`screen-${t}`).waitFor()
    const active = await page.getByTestId(`nav-${t}`).getAttribute('aria-selected')
    const font = await page.getByTestId('page-title').evaluate(el => getComputedStyle(el).fontFamily)
    check(active === 'true' && /Glacier Head/.test(font), `${t}: opens, tab active, title in the pixel font`)
  }
  const bodyFont = await page.evaluate(() => getComputedStyle(document.body).fontFamily)
  check(/Glacier Body/.test(bodyFont), 'body text uses the pixel body font')
  const fontsOk = await page.evaluate(async () => { await document.fonts.ready; return document.fonts.check('20px "Glacier Body"') && document.fonts.check('20px "Glacier Head"') })
  check(fontsOk, 'bundled pixel fonts loaded (offline)')

  await page.getByTestId('nav-automations').click()
  await page.getByTestId('flow-new').click()
  await page.getByTestId('flow-new-name').fill('Shell test')
  await page.getByTestId('flow-new-create').click()
  await page.getByTestId('env-name').waitFor()
  check(await page.getByTestId('env-name').inputValue() === 'Shell test', 'New opens the builder with the flow named')
  await page.getByTestId('save').click()
  await page.waitForFunction(() => document.querySelector('[data-testid=last-commit]')?.textContent !== '-')
  await page.getByTestId('nav-automations').click()
  await page.getByTestId('flow-shell-test').waitFor()
  check(true, 'saved flow appears in the Automations list')
  await page.getByTestId('flow-shell-test').click()
  await page.getByTestId('run-steps').waitFor()
  const titled = await page.waitForFunction(() => document.querySelector('[data-testid=page-title]')?.textContent === 'Shell test', null, { timeout: 8000 }).then(() => true, () => false)
  check(titled, 'clicking a flow opens its Run view')
  check(true, 'Run view opens')
  await page.getByTestId('run-history').click()
  await page.getByTestId('past-runs').waitFor()
  check(true, 'Past runs view opens')
  await page.goBack()
  await page.getByTestId('open-builder').click()
  const named = await page.waitForFunction(() => document.querySelector('[data-testid=env-name]')?.value === 'Shell test', null, { timeout: 8000 }).then(() => true, () => false)
  check(named, 'Edit flow opens the builder')

  // friendly editor: new note, then a second note that links to it via [[ suggestions, then undo
  await page.getByTestId('nav-memory').click()
  await page.getByTestId('note-new').click()
  await page.getByTestId('note-title').fill('Shopping list')
  await page.getByTestId('note-body').fill('milk and eggs')
  await page.getByTestId('note-save').click()
  await page.getByTestId('note-saved').waitFor()
  check(/milk and eggs/.test(await page.getByTestId('memory-note-body').textContent()), 'new note saved and shown')
  check(/Written by/.test(await page.getByTestId('note-trust').textContent()), 'note shows who wrote it')
  await page.getByTestId('note-new').click()
  await page.getByTestId('note-title').fill('Weekend plan')
  await page.getByTestId('note-body').click()
  await page.keyboard.type('buy things from [[Shop')
  await page.getByTestId('link-suggest').waitFor()
  await page.keyboard.press('Enter')
  check((await page.getByTestId('note-body').inputValue()).includes('[[shopping-list]]'), 'typing [[ suggests notes and inserts a link')
  await page.getByTestId('note-save').click()
  await page.getByTestId('note-saved').waitFor()
  await page.getByText('Links to').waitFor()
  check(true, 'saved note shows its outgoing link')
  await page.getByTestId('note-edit').click()
  await page.getByTestId('note-body').fill('buy things from [[shopping-list]] and [[someday-plan]]')
  await page.getByTestId('note-save').click()
  await page.getByTestId('link-unwritten').waitFor()
  check(/someday-plan \(not written yet\)/.test(await page.getByTestId('link-unwritten').textContent()), 'a link to a missing note says "not written yet"')
  await page.getByTestId('note-edit').click()
  await page.getByTestId('note-body').fill('changed my mind')
  await page.getByTestId('note-save').click()
  await page.getByTestId('note-saved').waitFor()
  await page.getByTestId('note-undo').click()
  await page.waitForFunction(() => /\[\[shopping-list\]\]/.test(document.querySelector('[data-testid=memory-note-body]')?.textContent ?? ''))
  check(true, 'Undo restores the previous version')
  await page.getByTestId('mem-note-shopping-list.md').click()
  await page.getByTestId('note-rename').click()
  await page.getByTestId('note-rename-input').fill('groceries')
  await page.getByTestId('note-rename-save').click()
  await page.getByTestId('note-renamed').waitFor()
  check(/groceries/.test(page.url()) && /Links to it were updated/.test(await page.getByTestId('note-renamed').textContent()), 'Rename moves the note and says links were updated')
  await page.getByTestId('mem-note-weekend-plan.md').click()
  await page.waitForFunction(() => /\[\[groceries\]\]/.test(document.querySelector('[data-testid=memory-note-body]')?.textContent ?? ''))
  check(true, 'notes that linked to the old name now link to the new one')
  await page.getByTestId('note-rename-undo').click()
  await page.waitForFunction(() => /shopping-list/.test(location.hash + location.pathname))
  await page.getByTestId('mem-note-weekend-plan.md').click()
  await page.waitForFunction(() => /\[\[shopping-list\]\]/.test(document.querySelector('[data-testid=memory-note-body]')?.textContent ?? ''))
  check(true, 'Undo puts the old name and its links back')

  // memory views: map, add (text + file), cleanup with undo
  await page.getByTestId('nav-memory').click()
  await page.getByTestId('memview-map').click()
  await page.getByTestId('memory-map').locator('canvas').waitFor()
  check(true, 'memory map draws the graph')
  await fetch(`http://localhost:${MOCK_PORT}/api/memory/note`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ path: 'live/demo.md', body: '# Live demo', author: 'owner' }) })
  const lit = await page.getByTestId('memory-live').waitFor({ timeout: 8000 }).then(() => true, () => false)
  check(lit, 'memory map lights up a note the moment it is written')
  await page.getByTestId('memview-add').click()
  await page.getByTestId('add-tab-text').click()
  await page.getByTestId('add-title').fill('Pasted idea')
  await page.getByTestId('add-text').fill('a thing to remember')
  await page.getByTestId('add-go').click()
  await page.getByTestId('add-result-0').waitFor()
  check(/saved/.test(await page.getByTestId('add-result-0').textContent()), 'Add > Text saves a note')
  await page.getByTestId('add-tab-files').click()
  await page.getByTestId('add-input').setInputFiles({ name: 'hello.txt', mimeType: 'text/plain', buffer: Buffer.from('hello') })
  await page.getByTestId('add-go').click()
  await page.getByTestId('add-result-0').waitFor()
  check(/added/.test(await page.getByTestId('add-result-0').textContent()), 'Add > Files uploads a file')
  await page.getByTestId('add-tab-chats').click()
  await page.getByTestId('import-refresh').click()
  await page.getByTestId('add-result-0').waitFor()
  check(/added/.test(await page.getByTestId('add-result-0').textContent()), 'Chat import: Check for new chats refreshes')
  await page.getByTestId('add-tab-sessions').click()
  await page.getByTestId('session-0').click()
  await page.getByTestId('session-detail').waitFor()
  check(/OpenCode/.test(await page.getByTestId('session-detail').textContent()), 'Coding sessions: an OpenCode session opens read-only')
  await page.getByTestId('session-save').click()
  await page.getByTestId('add-result-0').waitFor()
  check(/saved as sessions\//.test(await page.getByTestId('add-result-0').textContent()), 'Coding sessions: Save to memory saves a note')
  await page.getByTestId('memview-cleanup').click()
  await page.getByTestId('cleanup-h1').click()
  await page.getByTestId('cleanup-apply').click()
  await page.getByTestId('cleanup-undo-0').waitFor()
  check(true, 'cleanup applies a suggestion and offers Undo')

  // settings sections: models, secrets (save + remove, value never shown), usage, data, about
  await page.getByTestId('nav-settings').click()
  await page.getByTestId('settings-models').first().click()
  await page.getByTestId('ask-route').waitFor()
  check(/local model/.test(await page.getByTestId('ask-route').textContent()), 'Settings > Models says which assistant Ask uses and why')
  check(/qwen3/.test(await page.getByTestId('model-in-use').textContent()), 'Settings > Models shows the model in use')
  for (const sec of ['usage', 'data', 'about']) {
    await page.getByTestId(`settings-${sec}`).first().click()
    await page.locator(`[data-testid="settings-${sec}"].g-panel`).waitFor()
  }
  check(true, 'Settings > Usage, Data and About open')
  await page.getByTestId('settings-secrets').first().click()
  await page.getByTestId('secret-name').fill('TEST_KEY')
  await page.getByTestId('secret-value').fill('super-secret-value')
  await page.getByTestId('secret-save').click()
  await page.getByTestId('secret-TEST_KEY').waitFor()
  check(!(await page.content()).includes('super-secret-value'), 'Settings > Secrets saves a secret and never shows its value')
  await page.getByTestId('secret-del-TEST_KEY').click()
  await page.getByTestId('secret-del-yes-TEST_KEY').click()
  await page.getByTestId('secret-TEST_KEY').waitFor({ state: 'detached' })
  check(true, 'Settings > Secrets removes a secret after confirming')

  // Ask > Edit: proposed automation opens in the builder; its goal and checks survive saving
  await page.getByTestId('nav-ask').click()
  await page.getByTestId('chat-input').fill('make me a daily backup')
  await page.getByTestId('chat-send').click()
  await page.getByTestId('proposal-checks').waitFor()
  check(/You confirm: Did the backup finish\?/.test(await page.getByTestId('proposal-checks').textContent()), 'Ask shows how a proposed automation will be checked before it runs')
  await page.getByTestId('chat-title').waitFor()
  check(/make me a daily backup/.test(await page.getByTestId('chat-title').textContent()), 'a new chat is titled from the first question')
  await page.getByTestId('chat-rename').click()
  await page.getByTestId('chat-rename-input').fill('Backup planning')
  await page.getByTestId('chat-rename-save').click()
  await page.waitForFunction(() => /Backup planning/.test(document.querySelector('[data-testid=chat-title]')?.textContent ?? ''))
  check(true, 'Rename changes the chat title')
  await page.getByTestId('askview-past').click()
  await page.getByText('Backup planning').waitFor()
  await page.getByTestId('past-search').fill('nothing-like-this')
  await page.getByText('No chats match.').waitFor()
  await page.getByTestId('past-search').fill('backup')
  await page.getByText('Backup planning').click()
  await page.getByTestId('proposal-checks').waitFor({ state: 'detached' }).catch(() => {})
  check(/I can help|Creates a daily backup flow/.test(await page.getByTestId('chat-log').textContent()), 'Past chats: search finds a chat and reopening it shows its messages')
  await page.getByTestId('chat-new').click()
  check(await page.getByTestId('chat-title').count() === 0, 'New chat starts empty')
  await fetch(`http://localhost:${MOCK_PORT}/api/environments/ask-run-demo`, { method: 'PUT', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ id: 'ask-run-demo', name: 'Morning summary', nodes: [{ id: 'say', type: 'command', config: { cmd: 'echo hi' }, position: { x: 0, y: 0 } }], edges: [] }) })
  await page.getByTestId('chat-input').fill('run my Morning summary now')
  await page.getByTestId('chat-send').click()
  await page.getByTestId('proposal-run').click()
  await page.getByTestId('proposal-run-status').waitFor()
  check(await page.getByTestId('proposal-view-run').count() === 1, 'Ask: "run my ... now" asks first, then starts the run and links to it')
  await page.getByTestId('chat-new').click()
  await page.getByTestId('chat-input').fill('make me a daily backup')
  await page.getByTestId('chat-send').click()
  await page.getByTestId('proposal-checks').waitFor()
  await page.getByTestId('proposal-edit').click()
  const drafted = await page.waitForFunction(() => document.querySelector('[data-testid=env-name]')?.value === 'Daily backup', null, { timeout: 8000 }).then(() => true, () => false)
  check(drafted && await page.getByTestId('node-backup').count() === 1, 'Ask > Edit opens the proposed flow in the builder')
  await page.getByTestId('save').click()
  await page.waitForFunction(() => document.querySelector('[data-testid=last-commit]')?.textContent !== '-')
  const savedFlow = await (await fetch(`http://localhost:${MOCK_PORT}/api/environments/daily-backup`)).json()
  check(savedFlow.goal && Array.isArray(savedFlow.acceptance) && savedFlow.acceptance.length === 1, 'saving keeps the goal and checks the builder does not show')
  await page.getByTestId('env-name').fill('Daily backup renamed')
  await page.getByTestId('save').click()
  await page.getByTestId('version-restore-1').waitFor()
  await page.getByTestId('version-restore-1').click()
  await page.getByTestId('version-restore-yes-1').click()
  const restored = await page.waitForFunction(() => document.querySelector('[data-testid=env-name]')?.value === 'Daily backup', null, { timeout: 8000 }).then(() => true, () => false)
  check(restored && /Restored the version/.test(await page.getByTestId('message').textContent()), 'Saved versions: Restore brings back an earlier version of a flow')

  // Detail level: Simple hides advanced step types and technical fields; Full shows raw step settings
  await page.getByTestId('nav-settings').click()
  await page.getByTestId('layout-simple').click()
  await page.getByTestId('nav-automations').click()
  await page.goto(UI + '/#/automations/build/daily-backup')
  await page.getByTestId('palette').waitFor()
  check(await page.getByTestId('palette-loop').count() === 0 && await page.getByTestId('palette-command').count() === 1 && await page.getByTestId('env-id').count() === 0, 'Simple detail level hides advanced steps and technical fields')
  await page.goto(UI + '/#/settings/general')
  await page.getByTestId('layout-standard').click()
  // Run view: plain-language "What happened" explanation of a finished run
  const M = `http://localhost:${MOCK_PORT}`
  await fetch(`${M}/api/environments/explain-me`, { method: 'PUT', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ id: 'explain-me', name: 'Explain me', nodes: [{ id: 'n1', type: 'command', config: { cmd: 'echo hi' }, position: { x: 0, y: 0 } }], edges: [] }) })
  const { run_id: exRun } = await (await fetch(`${M}/api/environments/explain-me/run`, { method: 'POST' })).json()
  for (let i = 0; i < 50 && (await (await fetch(`${M}/api/runs/${exRun}`)).json()).status === 'running'; i++) await new Promise(r => setTimeout(r, 100))
  await page.goto(UI + `/#/automations/flow/explain-me/${exRun}`)
  const why = await page.getByTestId('run-why').waitFor({ timeout: 8000 }).then(() => true, () => false)
  check(why && /What happened/.test(await page.getByTestId('run-why').textContent()), 'Run view explains a run in plain words')

  // claims: list from Home, detail, decision
  await page.getByTestId('nav-home').click()
  await page.getByTestId('all-claims').click()
  await page.getByTestId('claim-c0ffee01').click()
  await page.getByTestId('claim-banner').waitFor()
  check(/eBay/.test(await page.getByTestId('claim-banner').textContent()) && /analyzed 12 categories/.test(await page.getByTestId('claim-research').textContent()), 'claim detail shows problem and research')
  await page.getByTestId('claim-more').click()
  await page.getByTestId('claim-done').waitFor()
  check(/researching/.test(await page.getByTestId('claim-banner').textContent()), 'Ask for more research updates the claim')
  await page.getByTestId('nav-home').click()
  await page.getByTestId('all-claims').click()
  await page.getByTestId('claim-c0ffee02').click()
  await page.getByTestId('claim-approve').click()
  await page.getByTestId('claim-rerun').waitFor()
  await page.getByTestId('claim-rerun').click()
  const reran = await page.waitForFunction(() => location.hash.startsWith('#/automations/flow/nightly-sync/'), null, { timeout: 8000 }).then(() => true, () => false)
  check(reran, 'after approving, "Run it again to check" re-runs the flow and opens the run')

  // templates: gallery -> use -> builder with the new flow
  await page.getByTestId('nav-automations').click()
  await page.getByTestId('flow-templates').click()
  await page.getByTestId('tpl-tpl-folder-backup').click()
  await page.getByTestId('tpl-use').click()
  const tplOk = await page.waitForFunction(() => document.querySelector('[data-testid=env-name]')?.value === 'Folder backup', null, { timeout: 8000 }).then(() => true, () => false)
  check(tplOk, 'Use this template creates the flow and opens it')

  await page.keyboard.press('Control+k')
  await page.getByTestId('command-palette').waitFor()
  await page.getByTestId('command-input').fill('memory')
  await page.keyboard.press('Enter')
  await page.getByTestId('screen-memory').waitFor()
  check(true, 'Ctrl+K palette jumps to Memory')
  await page.keyboard.press('Control+Tab')
  await page.getByTestId('screen-settings').waitFor()
  check(true, 'Ctrl+Tab moves to the next option')

  check(errors.length === 0, `no page errors${errors.length ? ': ' + errors.join(' | ') : ''}`)
} catch (e) { console.error(e); failures++ } finally { await browser?.close(); cleanup() }
console.log(failures ? `FAIL (${failures})` : 'PASS')
process.exit(failures ? 1 : 0)
